export const fortunes = [
  '"Any fool can write code that a computer can understand. Good programmers write code that humans can understand." - Martin Fowler',
  '"First, solve the problem. Then, write the code." - John Johnson',
  '"Experience is the name everyone gives to their mistakes." - Oscar Wilde',
  '"In order to be irreplaceable, one must always be different." - Coco Chanel',
  '"Java is to JavaScript what car is to carpet." - Chris Heilmann',
  '"Knowledge is power." - Francis Bacon',
  '"Fix the cause, not the symptom." - Steve Maguire',
  '"Simplicity is the soul of efficiency." - Austin Freeman',
  '"Make it work, make it right, make it fast." - Kent Beck',
  '"Code is like humor. When you have to explain it, it\'s bad." - Cory House',
  '"Before software can be reusable it first has to be usable." - Ralph Johnson',
  '"The best error message is the one that never shows up." - Thomas Fuchs',
  '"Programming isn\'t about what you know; it\'s about what you can figure out." - Chris Pine',
  '"The only way to learn a new programming language is by writing programs in it." - Dennis Ritchie',
  '"Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday\'s code." - Dan Salomon',
  '"Deleted code is debugged code." - Jeff Sickel',
  '"If debugging is the process of removing software bugs, then programming must be the process of putting them in." - Edsger W. Dijkstra',
  '"Talk is cheap. Show me the code." - Linus Torvalds',
  '"Programs must be written for people to read, and only incidentally for machines to execute." - Harold Abelson',
  '"Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live." - John Woods',
];
